services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./backend/redis:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lfu
    networks:
      - appnet

  mariadb:
    image: mariadb:11
    env_file:
      - .env.dev

    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      timeout: 5s
      interval: 5s
      retries: 5
    networks:
      - appnet

  backend:
    build: ./backend
    env_file:
      - .env.dev
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - appnet
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - Helpers/cron.schedules.Photos.ts
            - Helpers/cron.schedules.Articles.ts
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    ports:
      - '127.0.0.1:5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_DEV_SERVER=true
      - VITE_SERVER_URL=https://be-curious.fr
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  db_data:
  frontend_node_modules:

networks:
  appnet:
    driver: bridge
