services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    restart: unless-stopped
    volumes:
      - ./backend/redis:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lfu
    networks:
      - appnet

  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${DB_ROOT_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - appnet
    ports:
      - '${DB_PORT:-3306}:3306'

  backend:
    build: ./backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - appnet
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - Helpers/cron.schedules.Photos.ts
            - Helpers/cron.schedules.Articles.ts
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build:
      context: ./frontend
    ports:
      - '${FRONTEND_PORT:-5173}:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_DEV_SERVER=${VITE_DEV_SERVER}
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    depends_on:
      - backend
    networks:
      - appnet
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json

volumes:
  db_data:

networks:
  appnet:
    driver: bridge